[PHP]
; Fehlerdarstellung (für Entwicklung; in Produktion auf Off/0 setzen)
display_errors = Off
log_errors = On
error_log = /proc/self/fd/2

; Upload- und Laufzeitlimits
upload_max_filesize = 32M
post_max_size = 32M
max_execution_time = 60
memory_limit = 256M

; Zeitzone
date.timezone = Europe/Berlin

; Session-Konfiguration
session.cookie_httponly = 1
session.cookie_secure = 0   ; Auf 1 setzen wenn HTTPS genutzt wird
session.use_strict_mode = 1

[mail]
; Mailpit als lokaler SMTP-Server
SMTP = mailpit
smtp_port = 1025
