<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Erstellt das initiale Schema (recipe, ingredient, step).
 * Diese Migration fehlte in der Historie; das Schema wurde ursprünglich
 * ohne Migration angelegt.
 */
final class Version20260409202100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initiales Schema: recipe, ingredient, step';
    }

    public function up(Schema $schema): void
    {
        // Idempotent: auf Datenbanken, die vor dieser Migration bereits per
        // schema:update angelegt wurden, existieren die Tabellen schon.
        if ($schema->hasTable('recipe')) {
            return;
        }

        $this->addSql('CREATE TABLE ingredient (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount VARCHAR(50) DEFAULT NULL, unit VARCHAR(50) DEFAULT NULL, name VARCHAR(255) NOT NULL, group_name VARCHAR(255) DEFAULT NULL, position INT NOT NULL, recipe_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6BAF787059D8A214 ON ingredient (recipe_id)');
        $this->addSql('CREATE TABLE recipe (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, author VARCHAR(255) NOT NULL, image_path VARCHAR(512) DEFAULT NULL, servings INT NOT NULL, prep_time INT NOT NULL, cook_time INT NOT NULL, difficulty VARCHAR(50) NOT NULL, rating NUMERIC(2, 1) NOT NULL, rating_count INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE step (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number INT NOT NULL, title VARCHAR(255) DEFAULT NULL, description TEXT NOT NULL, recipe_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_43B9FE3C59D8A214 ON step (recipe_id)');
        $this->addSql('ALTER TABLE ingredient ADD CONSTRAINT FK_6BAF787059D8A214 FOREIGN KEY (recipe_id) REFERENCES recipe (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE step ADD CONSTRAINT FK_43B9FE3C59D8A214 FOREIGN KEY (recipe_id) REFERENCES recipe (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        if (!$schema->hasTable('recipe')) {
            return;
        }

        $this->addSql('ALTER TABLE ingredient DROP CONSTRAINT FK_6BAF787059D8A214');
        $this->addSql('ALTER TABLE step DROP CONSTRAINT FK_43B9FE3C59D8A214');
        $this->addSql('DROP TABLE ingredient');
        $this->addSql('DROP TABLE recipe');
        $this->addSql('DROP TABLE step');
    }
}
