<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Rezept-Import: Herkunftsdaten, Ruhezeit und Tags.
 *
 * - recipe.source_url / source_name / imported_at halten fest, woher ein
 *   importiertes Rezept stammt. Der Unique-Index auf source_url verhindert
 *   Doppel-Importe; PostgreSQL lässt darin mehrere NULL zu, manuell
 *   angelegte Rezepte bleiben also unberührt.
 * - recipe.rest_time nimmt Ruhe-/Einweichzeiten auf (getrennt von cook_time).
 * - tag / recipe_tag speichern die Schlagwörter aus den Quell-APIs.
 */
final class Version20260814193824 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Rezept-Import: source_url/source_name/imported_at, rest_time und Tags';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_tag_name ON tag (name)');

        $this->addSql('CREATE TABLE recipe_tag (recipe_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (recipe_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_72DED3CF59D8A214 ON recipe_tag (recipe_id)');
        $this->addSql('CREATE INDEX IDX_72DED3CFBAD26311 ON recipe_tag (tag_id)');
        $this->addSql('ALTER TABLE recipe_tag ADD CONSTRAINT FK_72DED3CF59D8A214 FOREIGN KEY (recipe_id) REFERENCES recipe (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recipe_tag ADD CONSTRAINT FK_72DED3CFBAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE NOT DEFERRABLE');

        // DEFAULT 0 ist nötig, damit die Spalte auf bestehenden Zeilen NOT NULL
        // sein kann; danach wieder entfernen, da die Entität den Default setzt.
        $this->addSql('ALTER TABLE recipe ADD rest_time INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE recipe ALTER COLUMN rest_time DROP DEFAULT');

        $this->addSql('ALTER TABLE recipe ADD source_url VARCHAR(1024) DEFAULT NULL');
        $this->addSql('ALTER TABLE recipe ADD source_name VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE recipe ADD imported_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_recipe_source_url ON recipe (source_url)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE recipe_tag DROP CONSTRAINT FK_72DED3CF59D8A214');
        $this->addSql('ALTER TABLE recipe_tag DROP CONSTRAINT FK_72DED3CFBAD26311');
        $this->addSql('DROP TABLE recipe_tag');
        $this->addSql('DROP TABLE tag');

        $this->addSql('DROP INDEX UNIQ_recipe_source_url');
        $this->addSql('ALTER TABLE recipe DROP rest_time');
        $this->addSql('ALTER TABLE recipe DROP source_url');
        $this->addSql('ALTER TABLE recipe DROP source_name');
        $this->addSql('ALTER TABLE recipe DROP imported_at');
    }
}
