<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/** Persistente Rezeptbewertungen mit anonymem Erhalt bei Kontolöschung. */
final class Version20260816150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Einzelbewertungen anlegen und nicht belegbare Legacy-Aggregate zurücksetzen';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE recipe_rating (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, recipe_id INT NOT NULL, user_id INT DEFAULT NULL, score SMALLINT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id), CONSTRAINT CHK_recipe_rating_score CHECK (score BETWEEN 1 AND 5))');
        $this->addSql('CREATE INDEX IDX_5597380359D8A214 ON recipe_rating (recipe_id)');
        $this->addSql('CREATE INDEX IDX_55973803A76ED395 ON recipe_rating (user_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_recipe_rating_user ON recipe_rating (recipe_id, user_id)');
        $this->addSql('ALTER TABLE recipe_rating ADD CONSTRAINT FK_recipe_rating_recipe FOREIGN KEY (recipe_id) REFERENCES recipe (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recipe_rating ADD CONSTRAINT FK_recipe_rating_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql("UPDATE recipe SET rating = '0.0', rating_count = 0");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE recipe_rating');
    }
}
